name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, dom, json, libxml, tokenizer, xml, xmlwriter

      - name: Install composer dependencies
        run: composer install --prefer-dist

      - name: Run PHPUnit
        run: vendor/bin/phpunit
